language: python

python:
    - "3.5"
    - "3.6"

services:
    - postgresql

before_script:
    - psql -c "CREATE USER ongebo WITH PASSWORD 'nothing'" -U postgres
    - psql -c "CREATE DATABASE testdb;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO ongebo"

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
    - pip install flask
    - pip install psycopg2
    - pip install flask-jwt-extended
    - pip install flasgger

script:
    - python fastfoodfast/db_setup.py testdb
    - pytest --cov=fastfoodfast

after_success:
    - coveralls