language: python

python:
    - "3.5"
    - "3.6"

services:
    - postgresql

before_script:
    - psql -c "CREATE USER ongebo WITH PASSWORD 'nothing'" -U postgres
    - psql -c "CREATE DATABASE fffdb;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE fffdb TO ongebo"

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
    - pip install flask
    - pip install psycopg2

script:
    - pytest --cov=fastfoodfast

after_success:
    - coveralls