language: python

python:
    - "3.5"
    - "3.6"

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls

script:
    - pytest --cov=fastfoodfast

after_success:
    - coveralls